spring:
  application:
    name: data-loader
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode  # Qwen的OpenAI式Endpoint
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
            model: qwen3.5-plus
      embedding:  # 新增嵌入模型配置
        options:
          model: text-embedding-v2  # 阿里云支持的嵌入模型
    vectorstore:
      qdrant:
        host: 127.0.0.1
        port: 6334
        api-key: ${QDRANT_API_KEY}
        initialize-schema: true
        collection-name: ai_demo
  cloud:
    function:
      definition: fileSupplier|documentReader|splitter|titleDeterminer|vectorStoreConsumer
server:
  port: 0
file:
  supplier:
    directory: /var/dropoff
    filename-regex: .*\.(pdf|docx|txt)
